// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcSzUITlPPAbxnvWEG1bLBVaEB4MV6wpk',
    appId: '1:110452505671:android:b087118cbcdf5f683fc562',
    messagingSenderId: '110452505671',
    projectId: 'tiger-1f080',
    storageBucket: 'tiger-1f080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JosgKVZvZIjzq67ffOYMLo4OMnius_w',
    appId: '1:110452505671:ios:a933e6adfa2e90483fc562',
    messagingSenderId: '110452505671',
    projectId: 'tiger-1f080',
    storageBucket: 'tiger-1f080.appspot.com',
    iosClientId: '110452505671-5fan6mame6oj3okpdj8bgfe0ov67jejv.apps.googleusercontent.com',
    iosBundleId: 'com.tiger.app',
  );
}
